# Generated by Django 6.0.6 on 2026-07-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='summary2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='summary3',
            field=models.TextField(blank=True),
        ),
    ]
