# Generated by Django 6.0.6 on 2026-07-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_personalinformation_summary2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='summary2',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='summary3',
        ),
    ]
