# Generated by Django 6.0.6 on 2026-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_personalinformation_summary2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='headline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
